"""Add project_table  Association Tab

Revision ID: 0e031220a301
Revises: e4882931c9a6
Create Date: 2023-04-14 15:11:34.191839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e031220a301'
down_revision = 'e4882931c9a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
