"""Add project_table  Association Tab

Revision ID: 40feedc60930
Revises: 4c12acef7605
Create Date: 2023-04-14 15:09:04.704065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40feedc60930'
down_revision = '4c12acef7605'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
