"""Add project_table  Association Tab

Revision ID: 6bab1bc25bd7
Revises: 40feedc60930
Create Date: 2023-04-14 15:10:33.553447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bab1bc25bd7'
down_revision = '40feedc60930'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
