"""Add project_table  Association Tab

Revision ID: 9df7d6d39b19
Revises: 0e031220a301
Create Date: 2023-04-14 15:13:27.758817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df7d6d39b19'
down_revision = '0e031220a301'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
